title = "Radu Suciu"
baseURL = "https://radusuciu.com"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerms", "RSS", "sitemap", "robotsTXT", "404"]
pygmentsCodeFences = true
pygmentsUseClasses = true
sectionPagesMenu = "main"
enableGitInfo = true

[params]
    description = "My Personal Website."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Blog-like posts"
    url = "/posts/"
    weight = -110
  [[menu.main]]
    identifier = "snippets"
    name = "Snippets"
    title = "Snippets of code"
    url = "/snippets/"
    weight = -110